import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import dynamic from 'next/dynamic';
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

// SSRを無効にしてParticlesBackgroundを動的にインポート
const ParticlesBackground = dynamic(() => import('../components/modules/ParticlesBackground'), { ssr: false });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <ParticlesBackground />
        {children}
      </body>
    </html>
  )
}
